Feature to process the finishedPlay and finishedRecording
uol-t1g2/webrecorder pull request #26
Opened 2023-03-04 22:18 UTC by itoogii

In this feature request, I have added the code to process the messages from the Content script in the Popup window to show the Message in the textArea.

2023-03-04 22:20 UTC, itoogii commented
@agamm I couldn't test it as the finished recording message for now is not ending, as Max and Yul haven't finished the detachEventListener function yet. Can you please review my changes in the meantime and suggest if something looks off?

2023-03-07 14:47 UTC, agamm requested changes
A few minor changes.

2023-03-07 14:47 UTC, agamm commented on src/pages/Popup/Popup.jsx
> +    setTextContent(message);
Why do we need to add the text into the text area after playing? I would remove as we want to keep the textarea with the instructions to play again. This should only be changed after recording.

2023-03-07 14:47 UTC, agamm commented on src/pages/Popup/Popup.jsx
> +    //handle when play ended
Make sure your comments are consistent (spacing and capital case)

2023-03-07 15:06 UTC, agamm approved these changes
Great!

2023-03-07 15:06 UTC, merged